### ISSUE TITLE
POST prefix missing

### ISSUE THREAD

**Issue by ingted** [intellifactory/rest-api.sample#1]
With this code, I would never successfully post a json body (404 error)
```
| [<EndPoint "/api">] Api of Cors<ApiEndPoint>
```

Once I changed to this 
```
| [<EndPoint "POST /api">] Api of Cors<ApiEndPoint>
```

Then it works.

I am not sure but it seems like "POST" should be added right?

**Comment by giuliohome** [comment]
I see it [here](https://github.com/websharper-samples/PeopleAPI/blob/master/src/App.fs#L35).

And notice that you need also PUT and DELETE (they're below the line I referenced).

Maybe should you look at the way you call the api from your client?

**Comment by ingted** [comment]
Oops... Seems my bad. It should not be added before api endpoint or GET will not work...
(It works now, but I dont know what fixed my code... haha)

Thanks!!!
